apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 88 # Redirect all request on :80 to the node :80
      #targetPort: 80 implicite
      nodePort: 30080
  selector:
    # link this service with pod
    app: portal-noticias